export { default as users } from './user';
export { default as routes } from './route';
export { default as links } from './link';
export { default as groups } from './group';
export { default as contents } from './content';
export { default as sections } from './section';
export { default as mainPhoto } from './mainPhoto';
export { default as news } from './news';
export { default as slides } from './slide';
